version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: giftkaro-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Giftkaro
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Username@7766
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    container_name: giftkaro-db
    environment:
      MYSQL_ROOT_PASSWORD: Username@7766
      MYSQL_DATABASE: Giftkaro
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data:
